version: 1.0.{build}
image: 
  - Ubuntu
  - Visual Studio 2017
platform: 
  - x64
configuration: 
  - Release 

matrix:
  fast_finish: true

for:
  -
    matrix:
      only:
        - image: Ubuntu

    before_build:
      # note: due to the fact that every variable is enclosed in quotation marks in appveyor, 
      # just do it the old-fasioned way....
      - sh: export Qt5_DIR=$HOME/Qt/5.15.2/gcc_64/lib/cmake/Qt5
      - cmake . 

    build_script:
      - make 
      
    test_script:

  -
    matrix:
      only:
        - image: Visual Studio 2017

    install:
      - set Qt5_DIR=c:\Qt\5.13.2\msvc2017_64\lib\cmake\Qt5
      - set QTDIR=c:\Qt\5.13.2\msvc2017_64
      - set PATH=%PATH%;%QTDIR%\bin;
      - git submodule update --init --recursive

    before_build:
      - cmake -G "Visual Studio 15 2017 Win64" .
    
    build_script:
      - msbuild %APPVEYOR_PROJECT_NAME%.sln
