version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release
  - Debug

install:
    - set Qt5_DIR=c:\Qt\5.13.2\msvc2017_64\lib\cmake\Qt5
    - set QTDIR=c:\Qt\5.13.2\msvc2017_64
    - set PATH=%PATH%;%QTDIR%\bin;
    - git submodule update --init --recursive

before_build:
    - cmake -G "Visual Studio 15 2017 Win64" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
